import { MigrationInterface, QueryRunner } from "typeorm";

export class migrations1681590420449 implements MigrationInterface {
    name = 'migrations1681590420449'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "nfefacil"."numeronfe" DROP CONSTRAINT "fk_numeronfe_empresa"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pardigital" DROP CONSTRAINT "fk_pardigital_empresa"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."empresa" DROP CONSTRAINT "fk_empresa_cidade"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."fornecedor" DROP CONSTRAINT "fk_fornec_cidade"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."cliente" DROP CONSTRAINT "fk_cliente_cidade"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."aliquf" ALTER COLUMN "aliqicms" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."boleto" ADD CONSTRAINT "PK_b95cb77c026b2963089f016b91b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pardigital" ALTER COLUMN "empresa" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."empresa" ALTER COLUMN "margem_lucro" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."empresa" ALTER COLUMN "codcidade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."fornecedor" ALTER COLUMN "codcidade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."cliente" ALTER COLUMN "codcidade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."forma_pgto" ALTER COLUMN "qtde_parcelas" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."forma_pgto" ALTER COLUMN "dias_inicial" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."forma_pgto" ALTER COLUMN "dias_intervalo" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."ibpt" ALTER COLUMN "aliqnacionalfederal" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."ibpt" ALTER COLUMN "aliqimportadosfederal" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."ibpt" ALTER COLUMN "aliqestadual" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."ibpt" ALTER COLUMN "aliqmunicipal" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."leiturax" ALTER COLUMN "valor" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."margem" ALTER COLUMN "margem" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."movfin" ALTER COLUMN "valor" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."movfin" ALTER COLUMN "valor_pago" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "valor_produtos" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "valor_descontos" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "valor_total" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "qtde_volume" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "peso_volume" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "numero_nfe" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "icms_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "icms_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "ipi_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "ipi_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "pis_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "pis_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "cofins_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "cofins_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "vtottrib" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "num_nfe_fat" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "num_nfe_dev" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "vtotibpt" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "valor_produtos" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "valor_descontos" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "valor_total" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "qtde_volume" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "peso_volume" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "numero_nfe" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "icms_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "icms_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "ipi_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "ipi_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "pis_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "pis_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "cofins_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "cofins_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "num_nfe_fat" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "num_nfe_dev" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prazo" ALTER COLUMN "parcela" SET DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prazo" ALTER COLUMN "vlr_parcela" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prazo" ALTER COLUMN "vlr_pago" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "numero_nfe" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "item" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "quantidade" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "vlr_unitario" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "vlr_produto" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "vlr_desconto" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "vlr_total" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "icms_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "icms_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "icms_pred" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "icms_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "ipi_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "ipi_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "ipi_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "pis_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "pis_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "pis_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "cofins_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "cofins_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "cofins_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "item" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "quantidade" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "quantidade" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vlr_unitario" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vlr_produto" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vlr_desconto" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vlr_total" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "icms_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "icms_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "icms_pred" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "icms_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "ipi_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "ipi_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "ipi_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "pis_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "pis_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "pis_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "cofins_bc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "cofins_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "cofins_vlr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vtottrib" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "preco_custo" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vtotibpt" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "valor_produtos" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "valor_descontos" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "valor_total" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "qtde_volume" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "peso_volume" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "numero_nfe" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "preco_compra" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "preco" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "estoque" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "garantia" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "icms_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "icms_pred" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "ipi_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "pis_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "cofins_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "trib_st_perc" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "item" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "quantidade" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "quantidade" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "vlr_unitario" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "vlr_produto" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "vlr_desconto" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "vlr_total" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."resumo_cst" ALTER COLUMN "valor_com_st" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."resumo_cst" ALTER COLUMN "valor_sem_st" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."sangria" ALTER COLUMN "valor" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."suprimento" ALTER COLUMN "valor" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."tipopgto65" ALTER COLUMN "valor" TYPE double precision(53)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "aliquf_pkey" ON "nfefacil"."aliquf" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "banco_pkey" ON "nfefacil"."banco" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "cxa_pkey" ON "nfefacil"."caixa" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "cfop_pkey" ON "nfefacil"."cfop" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "numeronfe_pkey" ON "nfefacil"."numeronfe" ("ambiente", "empresa", "modelonfe", "serienfe") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_pardigital" ON "nfefacil"."pardigital" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "empresa_pkey" ON "nfefacil"."empresa" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "fornec_pkey" ON "nfefacil"."fornecedor" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ibge_pkey" ON "nfefacil"."ibge" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "cliente_pkey" ON "nfefacil"."cliente" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "fpgto_pkey" ON "nfefacil"."forma_pgto" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ibpt_pkey" ON "nfefacil"."ibpt" ("ncm", "tipo", "uf") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_infresptec" ON "nfefacil"."inf_resp_tec" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "leiturax_pkey" ON "nfefacil"."leiturax" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_login" ON "nfefacil"."login" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "maq_pkey" ON "nfefacil"."maquina" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_margem" ON "nfefacil"."margem" ("cnpj") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "movfin_pkey" ON "nfefacil"."movfin" ("clifor", "data_mvto", "documento", "empresa", "parcela", "tipomovfin") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "nf_pkey" ON "nfefacil"."nf" ("empresa", "pedido") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "nfce_lido_pkey" ON "nfefacil"."nfce_lido" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "nfe_lido_pkey" ON "nfefacil"."nfe_lido" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_nf_ent" ON "nfefacil"."nf_entrada" ("cod_fornecedor", "empresa", "numero_nfe", "serie_nfe") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "nfprazo_pkey" ON "nfefacil"."nf_prazo" ("empresa", "parcela", "pedido") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "nfprodent_pkey" ON "nfefacil"."nf_prod_entra" ("cod_fornecedor", "empresa", "item", "numero_nfe", "serie_nfe") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "nfprod_pkey" ON "nfefacil"."nf_produtos" ("empresa", "item", "pedido") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "numerolote_pkey" ON "nfefacil"."numerolote" ("empresa", "numeroproximolote") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "numeropedido_pkey" ON "nfefacil"."numeropedido" ("empresa", "pedido") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "numeroseq_tef_pkey" ON "nfefacil"."numeroseq_tef" ("empresa", "numeroproximaseq") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "numerosequencia_pkey" ON "nfefacil"."numerosequencia" ("empresa", "numeroproximaseq") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ped65_pkey" ON "nfefacil"."pedidos65" ("empresa", "pedido") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pessoa_pkey" ON "nfefacil"."pessoa" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "produto_pkey" ON "nfefacil"."produto" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "prod65_pkey" ON "nfefacil"."produtos65" ("empresa", "item", "pedido") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "rescst_pkey" ON "nfefacil"."resumo_cst" ("empresa", "icms_cst", "pis_cst") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "sang_pkey" ON "nfefacil"."sangria" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "supri_pkey" ON "nfefacil"."suprimento" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tdoc_pkey" ON "nfefacil"."tipo_doc" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tpmvfin_pkey" ON "nfefacil"."tipomovfin" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipopgto_pkey" ON "nfefacil"."tipo_pgto" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idtpgto_pkey" ON "nfefacil"."tipopgto65" ("empresa", "id_tipo_pgto", "pedido") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uf_pkey" ON "nfefacil"."uf" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unidade_pkey" ON "nfefacil"."unidade" ("codigo") `);
        await queryRunner.query(`ALTER TABLE "nfefacil"."numeronfe" ADD CONSTRAINT "FK_3b6d369c045a73a1d1a1b64fa02" FOREIGN KEY ("empresa") REFERENCES "nfefacil"."empresa"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pardigital" ADD CONSTRAINT "FK_ef83629930448bbf7a206056378" FOREIGN KEY ("empresa") REFERENCES "nfefacil"."empresa"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."empresa" ADD CONSTRAINT "FK_601f54355f7988389c9b4c7d16e" FOREIGN KEY ("codcidade") REFERENCES "nfefacil"."ibge"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."fornecedor" ADD CONSTRAINT "FK_f45ec8edb9ad88ed4540a6a055c" FOREIGN KEY ("codcidade") REFERENCES "nfefacil"."ibge"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."cliente" ADD CONSTRAINT "FK_a26401190256c8171bb1ee33ef6" FOREIGN KEY ("codcidade") REFERENCES "nfefacil"."ibge"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "nfefacil"."cliente" DROP CONSTRAINT "FK_a26401190256c8171bb1ee33ef6"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."fornecedor" DROP CONSTRAINT "FK_f45ec8edb9ad88ed4540a6a055c"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."empresa" DROP CONSTRAINT "FK_601f54355f7988389c9b4c7d16e"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pardigital" DROP CONSTRAINT "FK_ef83629930448bbf7a206056378"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."numeronfe" DROP CONSTRAINT "FK_3b6d369c045a73a1d1a1b64fa02"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."unidade_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."uf_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."idtpgto_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."tipopgto_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."tpmvfin_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."tdoc_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."supri_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."sang_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."rescst_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."prod65_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."produto_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."pessoa_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."ped65_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."numerosequencia_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."numeroseq_tef_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."numeropedido_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."numerolote_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."nfprod_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."nfprodent_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."nfprazo_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."pk_nf_ent"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."nfe_lido_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."nfce_lido_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."nf_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."movfin_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."pk_margem"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."maq_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."pk_login"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."leiturax_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."pk_infresptec"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."ibpt_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."fpgto_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."cliente_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."ibge_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."fornec_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."empresa_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."pk_pardigital"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."numeronfe_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."cfop_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."cxa_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."banco_pkey"`);
        await queryRunner.query(`DROP INDEX "nfefacil"."aliquf_pkey"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."tipopgto65" ALTER COLUMN "valor" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."suprimento" ALTER COLUMN "valor" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."sangria" ALTER COLUMN "valor" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."resumo_cst" ALTER COLUMN "valor_sem_st" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."resumo_cst" ALTER COLUMN "valor_com_st" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "vlr_total" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "vlr_desconto" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "vlr_produto" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "vlr_unitario" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "quantidade" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "quantidade" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produtos65" ALTER COLUMN "item" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "trib_st_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "cofins_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "pis_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "ipi_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "icms_pred" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "icms_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "garantia" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "estoque" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "preco" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."produto" ALTER COLUMN "preco_compra" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "numero_nfe" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "peso_volume" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "qtde_volume" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "valor_total" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "valor_descontos" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pedidos65" ALTER COLUMN "valor_produtos" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vtotibpt" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "preco_custo" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vtottrib" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "cofins_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "cofins_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "cofins_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "pis_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "pis_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "pis_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "ipi_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "ipi_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "ipi_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "icms_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "icms_pred" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "icms_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "icms_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vlr_total" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vlr_desconto" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vlr_produto" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "vlr_unitario" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "quantidade" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "quantidade" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_produtos" ALTER COLUMN "item" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "cofins_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "cofins_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "cofins_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "pis_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "pis_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "pis_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "ipi_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "ipi_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "ipi_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "icms_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "icms_pred" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "icms_perc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "icms_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "vlr_total" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "vlr_desconto" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "vlr_produto" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "vlr_unitario" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "quantidade" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "item" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prod_entra" ALTER COLUMN "numero_nfe" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prazo" ALTER COLUMN "vlr_pago" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prazo" ALTER COLUMN "vlr_parcela" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_prazo" ALTER COLUMN "parcela" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "num_nfe_dev" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "num_nfe_fat" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "cofins_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "cofins_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "pis_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "pis_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "ipi_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "ipi_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "icms_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "icms_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "numero_nfe" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "peso_volume" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "qtde_volume" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "valor_total" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "valor_descontos" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf_entrada" ALTER COLUMN "valor_produtos" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "vtotibpt" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "num_nfe_dev" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "num_nfe_fat" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "vtottrib" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "cofins_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "cofins_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "pis_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "pis_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "ipi_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "ipi_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "icms_vlr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "icms_bc" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "numero_nfe" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "peso_volume" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "qtde_volume" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "valor_total" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "valor_descontos" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."nf" ALTER COLUMN "valor_produtos" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."movfin" ALTER COLUMN "valor_pago" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."movfin" ALTER COLUMN "valor" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."margem" ALTER COLUMN "margem" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."leiturax" ALTER COLUMN "valor" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."ibpt" ALTER COLUMN "aliqmunicipal" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."ibpt" ALTER COLUMN "aliqestadual" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."ibpt" ALTER COLUMN "aliqimportadosfederal" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."ibpt" ALTER COLUMN "aliqnacionalfederal" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."forma_pgto" ALTER COLUMN "dias_intervalo" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."forma_pgto" ALTER COLUMN "dias_inicial" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."forma_pgto" ALTER COLUMN "qtde_parcelas" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."cliente" ALTER COLUMN "codcidade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."fornecedor" ALTER COLUMN "codcidade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."empresa" ALTER COLUMN "codcidade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."empresa" ALTER COLUMN "margem_lucro" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pardigital" ALTER COLUMN "empresa" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."boleto" DROP CONSTRAINT "PK_b95cb77c026b2963089f016b91b"`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."aliquf" ALTER COLUMN "aliqicms" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."cliente" ADD CONSTRAINT "fk_cliente_cidade" FOREIGN KEY ("codcidade") REFERENCES "nfefacil"."ibge"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."fornecedor" ADD CONSTRAINT "fk_fornec_cidade" FOREIGN KEY ("codcidade") REFERENCES "nfefacil"."ibge"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."empresa" ADD CONSTRAINT "fk_empresa_cidade" FOREIGN KEY ("codcidade") REFERENCES "nfefacil"."ibge"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."pardigital" ADD CONSTRAINT "fk_pardigital_empresa" FOREIGN KEY ("empresa") REFERENCES "nfefacil"."empresa"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfefacil"."numeronfe" ADD CONSTRAINT "fk_numeronfe_empresa" FOREIGN KEY ("empresa") REFERENCES "nfefacil"."empresa"("codigo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
