import { MigrationInterface, QueryRunner } from "typeorm";

export class migrations1681589447880 implements MigrationInterface {
    name = 'migrations1681589447880'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" DROP CONSTRAINT "fk_natureza"`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" DROP CONSTRAINT "fk_tipoRelac"`);
        await queryRunner.query(`ALTER TABLE "apoio"."atendimentopadrao" ALTER COLUMN "descricao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."canalcomunicacao" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "descricao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "qtdDormitorios" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nroSuites" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nroLavabos" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nroDependencias" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nroSalas" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nraSacadas" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "idcCobertura" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."depreciacao" ALTER COLUMN "taxa" SET DEFAULT NULL::numeric`);
        await queryRunner.query(`ALTER TABLE "apoio"."equipe" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."estadocivil" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."formajuridica" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."localdachave" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."tiporelacionamento" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" ALTER COLUMN "idtiporelacionamento" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" ALTER COLUMN "idnaturezarelacionamento" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezarelacionamento" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."porte" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."postoavancado" ALTER COLUMN "codigounidadeoperacional" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."postoavancado" ALTER COLUMN "codigoposto" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."postoavancado" ALTER COLUMN "nomeposto" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."programafomento" ALTER COLUMN "codigo" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "apoio"."regiao" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."setorfinaciavel" ALTER COLUMN "denominacao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "apoio"."situacaoimovel" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."situacaoreceita" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."subtiporegistro" ALTER COLUMN "IdSubTipoRegistro" SET DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE "apoio"."subtiporegistro" ALTER COLUMN "prefixo" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."subtiporegistro" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."tipodeimovel" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."tipoendereco" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."tipoescritura" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."tipoprovadocumental" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."tiporegistro" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."tiporesidencia" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."unidade" ALTER COLUMN "codigo" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "apoio"."unidade" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`ALTER TABLE "apoio"."vista" ALTER COLUMN "denominacao" SET DEFAULT NULL::bpchar`);
        await queryRunner.query(`CREATE UNIQUE INDEX "anunciopadrao_pkey" ON "apoio"."anunciopadrao" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "atendimentopadrao_pkey" ON "apoio"."atendimentopadrao" ("idAtendimentoPadrao") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "atividadeprodutiva_pkey" ON "apoio"."atividadeprodutiva" ("idAtividadeProdutiva") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "canalcomunicacao_pkey" ON "apoio"."canalcomunicacao" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "caracteristicaapartamento_pkey" ON "apoio"."caracteristicaapartamento" ("idCaractApto") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "centrocusto_pkey" ON "apoio"."centrocusto" ("idcentrocusto") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "controleSiscad_pkey" ON "apoio"."controleSiscad" ("idcontrole") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "custostotais_pkey" ON "apoio"."custostotais" ("idcustosTotais") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "depreciacao_pkey" ON "apoio"."depreciacao" ("idDepreciacao") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "despesasoperacionais_pkey" ON "apoio"."despesasoperacionais" ("iddespesasOperacionais") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "equipe_pkey" ON "apoio"."equipe" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "estadocivil_pkey" ON "apoio"."estadocivil" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "formajuridica_pkey" ON "apoio"."formajuridica" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "grupocentrocusto_pkey" ON "apoio"."grupocentrocusto" ("idgrupoCentroCusto") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "gruposalarios_pkey" ON "apoio"."gruposalarios" ("idgrupoSalarios") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "insumos_pkey" ON "apoio"."insumos" ("idInsumos") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "localdachave_pkey" ON "apoio"."localdachave" ("IdLocalChave") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tiporelacionamento_pkey" ON "apoio"."tiporelacionamento" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "naturezatipo_pkey" ON "apoio"."naturezatipo" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "naturezarelacionamento_pkey" ON "apoio"."naturezarelacionamento" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "porte_pkey" ON "apoio"."porte" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "postoavancado_pkey" ON "apoio"."postoavancado" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "programafomento_pkey" ON "apoio"."programafomento" ("idPrograma") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "regiao_pkey" ON "apoio"."regiao" ("IdRegiao") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "regimedebens_pkey" ON "apoio"."regimedebens" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "salarios_pkey" ON "apoio"."salarios" ("idsalarios") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "setorfinaciavel_pkey" ON "apoio"."setorfinaciavel" ("idsetor") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "setorfinanciavel_pkey" ON "apoio"."setorfinanciavel" ("idSetor") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "setormaoobra_pkey" ON "apoio"."setormaoobra" ("idsetorMaoObra") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "situacaoimovel_pkey" ON "apoio"."situacaoimovel" ("IdSituacaoImovel") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "situacaoreceita_pkey" ON "apoio"."situacaoreceita" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "situacaosiscad_pkey" ON "apoio"."situacaosiscad" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "subtiporegistro_pkey" ON "apoio"."subtiporegistro" ("IdSubTipoRegistro") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "sufixosiscad_pkey" ON "apoio"."sufixosiscad" ("idsufixo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipodeimovel_pkey" ON "apoio"."tipodeimovel" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipoendereco_pkey" ON "apoio"."tipoendereco" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipoescritura_pkey" ON "apoio"."tipoescritura" ("IdTipoEscritura") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipofinanciamento_pkey" ON "apoio"."tipofinanciamento" ("idtipoFinanciamento") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipoprovadocumental_pkey" ON "apoio"."tipoprovadocumental" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tiporegistro_pkey" ON "apoio"."tiporegistro" ("idTipoRegistro") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tiporesidencia_pkey" ON "apoio"."tiporesidencia" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unidade_pkey" ON "apoio"."unidade" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "vista_pkey" ON "apoio"."vista" ("IdVista") `);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" ADD CONSTRAINT "FK_c5dc51cb80798e1bf7c9caa3758" FOREIGN KEY ("idnaturezarelacionamento") REFERENCES "apoio"."naturezarelacionamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" ADD CONSTRAINT "FK_56f55b4a94d50736b3f1522af1b" FOREIGN KEY ("idtiporelacionamento") REFERENCES "apoio"."tiporelacionamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" DROP CONSTRAINT "FK_56f55b4a94d50736b3f1522af1b"`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" DROP CONSTRAINT "FK_c5dc51cb80798e1bf7c9caa3758"`);
        await queryRunner.query(`DROP INDEX "apoio"."vista_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."unidade_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."tiporesidencia_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."tiporegistro_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."tipoprovadocumental_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."tipofinanciamento_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."tipoescritura_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."tipoendereco_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."tipodeimovel_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."sufixosiscad_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."subtiporegistro_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."situacaosiscad_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."situacaoreceita_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."situacaoimovel_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."setormaoobra_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."setorfinanciavel_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."setorfinaciavel_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."salarios_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."regimedebens_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."regiao_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."programafomento_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."postoavancado_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."porte_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."naturezarelacionamento_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."naturezatipo_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."tiporelacionamento_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."localdachave_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."insumos_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."gruposalarios_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."grupocentrocusto_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."formajuridica_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."estadocivil_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."equipe_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."despesasoperacionais_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."depreciacao_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."custostotais_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."controleSiscad_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."centrocusto_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."caracteristicaapartamento_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."canalcomunicacao_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."atividadeprodutiva_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."atendimentopadrao_pkey"`);
        await queryRunner.query(`DROP INDEX "apoio"."anunciopadrao_pkey"`);
        await queryRunner.query(`ALTER TABLE "apoio"."vista" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."unidade" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."unidade" ALTER COLUMN "codigo" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."tiporesidencia" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."tiporegistro" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."tipoprovadocumental" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."tipoescritura" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."tipoendereco" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."tipodeimovel" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."subtiporegistro" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."subtiporegistro" ALTER COLUMN "prefixo" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."subtiporegistro" ALTER COLUMN "IdSubTipoRegistro" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "apoio"."situacaoreceita" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."situacaoimovel" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."setorfinaciavel" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."regiao" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."programafomento" ALTER COLUMN "codigo" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."postoavancado" ALTER COLUMN "nomeposto" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."postoavancado" ALTER COLUMN "codigoposto" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."postoavancado" ALTER COLUMN "codigounidadeoperacional" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."porte" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezarelacionamento" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" ALTER COLUMN "idnaturezarelacionamento" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" ALTER COLUMN "idtiporelacionamento" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."tiporelacionamento" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."localdachave" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."formajuridica" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."estadocivil" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."equipe" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."depreciacao" ALTER COLUMN "taxa" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "idcCobertura" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nraSacadas" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nroSalas" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nroDependencias" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nroLavabos" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "nroSuites" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "qtdDormitorios" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "apoio"."caracteristicaapartamento" ALTER COLUMN "descricao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."canalcomunicacao" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."atendimentopadrao" ALTER COLUMN "descricao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" ADD CONSTRAINT "fk_tipoRelac" FOREIGN KEY ("idtiporelacionamento") REFERENCES "apoio"."tiporelacionamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "apoio"."naturezatipo" ADD CONSTRAINT "fk_natureza" FOREIGN KEY ("idnaturezarelacionamento") REFERENCES "apoio"."naturezarelacionamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
