import { MigrationInterface, QueryRunner } from "typeorm";

export class migrations1681589870515 implements MigrationInterface {
    name = 'migrations1681589870515'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cup"."bemequipamento" DROP CONSTRAINT "fk_bemequip"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" DROP CONSTRAINT "fk_bemimovel"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" DROP CONSTRAINT "fk_laudobem"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmaquina" DROP CONSTRAINT "fk_maquinabem"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmovel" DROP CONSTRAINT "fk_imovelbem"`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonialvalores" DROP CONSTRAINT "fk_balancopatrim"`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonialvalores" DROP CONSTRAINT "fk_centrocustobal"`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonial" DROP CONSTRAINT "fk_balancocentrocusto"`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonial" DROP CONSTRAINT "fk_grupocentrocusto"`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonial" DROP CONSTRAINT "fk_pessoabalancopatr"`);
        await queryRunner.query(`ALTER TABLE "cup"."bensvinculados" DROP CONSTRAINT "fk_bemvinculado"`);
        await queryRunner.query(`ALTER TABLE "cup"."bensvinculados" DROP CONSTRAINT "fk_pessoavenculo"`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" DROP CONSTRAINT "fk_pessoacapital"`);
        await queryRunner.query(`ALTER TABLE "cup"."cargoocupacao" DROP CONSTRAINT "fk_ocupacaopessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."certidao" DROP CONSTRAINT "fk_certidaopessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."controlecapital" DROP CONSTRAINT "fk_pessoacapital"`);
        await queryRunner.query(`ALTER TABLE "cup"."dirigenteempresa" DROP CONSTRAINT "fk_dirigente"`);
        await queryRunner.query(`ALTER TABLE "cup"."dirigenteempresa" DROP CONSTRAINT "fk_empresa"`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" DROP CONSTRAINT "fk_pessoaendereco"`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" DROP CONSTRAINT "pessoaFisica"`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" DROP CONSTRAINT "pessoaJuridica"`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" DROP CONSTRAINT "fk_regimetripessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" DROP CONSTRAINT "fk_tipotributacao"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" DROP CONSTRAINT "fk_bemrelac"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" DROP CONSTRAINT "fk_relacbempessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" DROP CONSTRAINT "fk_pessoarelac"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" DROP CONSTRAINT "fk_relacpessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" DROP CONSTRAINT "fk_tiporelac"`);
        await queryRunner.query(`ALTER TABLE "cup"."renda" DROP CONSTRAINT "renda_idpessoa_fkey"`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" DROP CONSTRAINT "fk_telpessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."bempessoa" DROP CONSTRAINT "fk_bembens"`);
        await queryRunner.query(`ALTER TABLE "cup"."bempessoa" DROP CONSTRAINT "fk_bempessoas"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemproducaoagricola" DROP CONSTRAINT "fk_bemproducao"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemsemovente" DROP CONSTRAINT "fk_bemsemovente"`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" DROP CONSTRAINT "fk_caractercondominio"`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" DROP CONSTRAINT "fk_caractbem"`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" DROP CONSTRAINT "fk_comodosbem"`);
        await queryRunner.query(`ALTER TABLE "cup"."garagemvinculada" DROP CONSTRAINT "fk_bemgaragem"`);
        await queryRunner.query(`ALTER TABLE "cup"."garantia" DROP CONSTRAINT "fk_bemgarantia"`);
        await queryRunner.query(`ALTER TABLE "cup"."guiatransporte" DROP CONSTRAINT "fk_transportebem"`);
        await queryRunner.query(`ALTER TABLE "cup"."hipoteca" DROP CONSTRAINT "fk_bemhipoteca"`);
        await queryRunner.query(`ALTER TABLE "cup"."registro" DROP CONSTRAINT "fk_escriturabem"`);
        await queryRunner.query(`ALTER TABLE "cup"."seguro" DROP CONSTRAINT "fk_segurobem"`);
        await queryRunner.query(`ALTER TABLE "cup"."avaliacao" DROP CONSTRAINT "fk_avaliacaobem"`);
        await queryRunner.query(`ALTER TABLE "cup"."certidao" DROP CONSTRAINT "pk_certidoes"`);
        await queryRunner.query(`ALTER TABLE "cup"."certidao" ADD CONSTRAINT "pk_certidoes" PRIMARY KEY ("idcertidao", "idpessoa", "dataemissao", "numero")`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" DROP CONSTRAINT "pk_regimepessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" ADD CONSTRAINT "pk_regimepessoa" PRIMARY KEY ("idpessoa", "idregimetributacao")`);
        await queryRunner.query(`ALTER TABLE "cup"."bemequipamento" ADD CONSTRAINT "UQ_197dc040e56986b2a1f0eb58dc3" UNIQUE ("idbem")`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idbem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idsubtipobemimovel" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "nroapartamento" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idregimeobra" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "areatotal" SET DEFAULT NULL::numeric`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "areaconstruida" SET DEFAULT NULL::numeric`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "numeroimovelrf" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "numeroimovelincra" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaoimuneitr" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaocondominio" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaoexploracao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaopenhora" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "arealegal" SET DEFAULT NULL::numeric`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "areareal" SET DEFAULT NULL::numeric`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaoonus" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idtipoescritura" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idchabitese" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idaforamento" SET DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idregiao" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idlocalchave" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idprontaentrega" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idtipogas" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idchurrasqueira" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idesquina" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idcaracteristicas" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "sacadas" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idcomodos" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idcaracteristicacondominio" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idusuario" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idestacao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ALTER COLUMN "precocub" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ALTER COLUMN "percentualbdi" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ALTER COLUMN "valorcoisafeita" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ALTER COLUMN "valorfinal" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmaquina" ADD CONSTRAINT "UQ_80083602ff56d961706b60df0af" UNIQUE ("idbem")`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ALTER COLUMN "autorizado" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ALTER COLUMN "subscrito" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ALTER COLUMN "integralizado" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ALTER COLUMN "valorcota" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."cargoocupacao" ALTER COLUMN "denominacao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."cargoocupacao" ALTER COLUMN "status" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."controlecapital" ALTER COLUMN "valor" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."controlecapital" ALTER COLUMN "idpessoa" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "tipologradouro" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "complemento" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "perimetro" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "cep" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "caixapostal" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idtipoendereco" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idccorrespondencia" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "torre" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idusuario" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idestacao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "apelido" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "nomepai" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idestadocivil" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idsexo" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "profissao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "ufnaturalidade" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "registrogeral" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "orgaoemissor" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "ufrg" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "ndependente" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "codigousuariorede" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "status" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idusuario" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idestacao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "senha" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "numeroregistrojunta" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "orgaoexpedidor" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "inscricaoestadual" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "incentivoicms" SET DEFAULT NULL::numeric`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "optantesimples" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "grupoeconomico" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "inscricaomunicipal" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "idusuario" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "idestacao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" ALTER COLUMN "aliquota" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idproprietario" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idbem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idtipobem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idnaturezarelacionamento" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ALTER COLUMN "idnaturezatipo" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ALTER COLUMN "idpessoarelacionada" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ALTER COLUMN "numero" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ALTER COLUMN "pais" SET DEFAULT 55`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ALTER COLUMN "idccelular" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ALTER COLUMN "falarcom" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "cup"."pessoa_idpessoa_seq" OWNED BY "cup"."pessoa"."idpessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoa" ALTER COLUMN "idpessoa" SET DEFAULT nextval('"cup"."pessoa_idpessoa_seq"')`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoa" ALTER COLUMN "idpessoa" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idbem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcpilotis" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcduplaentrada" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcarealazer" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcelevador" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "tipoaquecedor" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "nomecondominio" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "nomecondominioabreviado" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcvidroisolamento" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "nropavimentos" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "torre" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "idbem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "qtdgaragens" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "identificacaogaragens" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "tipogaragem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "localizacaogaragem" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "idchobbybox" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "identificacaohobbybox" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "idcbombahidraulica" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "idbem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "qtddormitorios" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "nrosuites" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "nrosalas" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "nrolavabos" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "nrodependencias" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."garagemvinculada" ALTER COLUMN "idbem" SET DEFAULT 0`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "cup"."guiatransporte_idguiatransporte_seq" OWNED BY "cup"."guiatransporte"."idguiatransporte"`);
        await queryRunner.query(`ALTER TABLE "cup"."guiatransporte" ALTER COLUMN "idguiatransporte" SET DEFAULT nextval('"cup"."guiatransporte_idguiatransporte_seq"')`);
        await queryRunner.query(`ALTER TABLE "cup"."guiatransporte" ALTER COLUMN "idguiatransporte" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "cup"."seguro_idseguro_seq" OWNED BY "cup"."seguro"."idseguro"`);
        await queryRunner.query(`ALTER TABLE "cup"."seguro" ALTER COLUMN "idseguro" SET DEFAULT nextval('"cup"."seguro_idseguro_seq"')`);
        await queryRunner.query(`ALTER TABLE "cup"."seguro" ALTER COLUMN "idseguro" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "cup"."bem_idbem_seq" OWNED BY "cup"."bem"."idbem"`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idbem" SET DEFAULT nextval('"cup"."bem_idbem_seq"')`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idbem" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idtipobem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "referencia" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "nomebem" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "qtdbensassociados" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "situacaogarantia" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "valor" SET DEFAULT NULL::numeric`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idsituacaobem" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idestadoconservacao" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idade" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idcplaca" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idcfotos" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "sitioweb" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idanunciado" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idcdestaque" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idusuario" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idestacao" SET DEFAULT NULL::character varying`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "cup"."avaliacao_idavaliacao_seq" OWNED BY "cup"."avaliacao"."idavaliacao"`);
        await queryRunner.query(`ALTER TABLE "cup"."avaliacao" ALTER COLUMN "idavaliacao" SET DEFAULT nextval('"cup"."avaliacao_idavaliacao_seq"')`);
        await queryRunner.query(`ALTER TABLE "cup"."avaliacao" ALTER COLUMN "idavaliacao" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "cup"."bem_old_idbem_seq" OWNED BY "cup"."bem_old"."idbem"`);
        await queryRunner.query(`ALTER TABLE "cup"."bem_old" ALTER COLUMN "idbem" SET DEFAULT nextval('"cup"."bem_old_idbem_seq"')`);
        await queryRunner.query(`ALTER TABLE "cup"."bem_old" ALTER COLUMN "idbem" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "cup"."endereco_old_idendereco_seq" OWNED BY "cup"."endereco_old"."idendereco"`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco_old" ALTER COLUMN "idendereco" SET DEFAULT nextval('"cup"."endereco_old_idendereco_seq"')`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco_old" ALTER COLUMN "idendereco" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica_old" ALTER COLUMN "incentivoicms" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idsufixo" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idstatus" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idcontrole" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idrisco" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idrestritivo" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idimpeditivos" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."rendas" ALTER COLUMN "idpessoa" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."rendas" ALTER COLUMN "idtiporenda" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "cup"."rendas" ALTER COLUMN "valor" TYPE double precision(53)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_bemequipamento" ON "cup"."bemequipamento" ("idbem") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "bemimovel_pkey" ON "cup"."bemimovel" ("idbemimovel") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_bemlaudo" ON "cup"."bemlaudo" ("data", "idbem", "idlaudo", "idpessoa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_bemmaquina" ON "cup"."bemmaquina" ("idbem") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_bemmovel" ON "cup"."bemmovel" ("idbemmovel") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "balancopatrimonialvalores_pkey" ON "cup"."balancopatrimonialvalores" ("idbalancopatrimonial", "idbalancopatrimonialvalores") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_balancopatri" ON "cup"."balancopatrimonial" ("idbalancopatrimonial") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "bensvinculados_pkey" ON "cup"."bensvinculados" ("idbemvinculado") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "capitalsocial_pkey" ON "cup"."capitalsocial" ("idcapitalsocial") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "cargoocupacao_pkey" ON "cup"."cargoocupacao" ("idocupacao") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_certidoes" ON "cup"."certidao" ("dataemissao", "idpessoa", "numero") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "controlecapital_pkey" ON "cup"."controlecapital" ("idcontrolecapital") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_dirigenteempresa" ON "cup"."dirigenteempresa" ("idpessoafisica", "idpessoajuridica") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "endereco_pkey" ON "cup"."endereco" ("idendereco") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "fisica_pkey" ON "cup"."fisica" ("idfisica") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "juridica_pkey" ON "cup"."juridica" ("idjuridica") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_regimetributacao" ON "cup"."regimetributacao" ("idregimetributacao") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_regimepessoa" ON "cup"."pessoaregimetributacao" ("idpessoa", "idregimetributacao") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "relacionamentobempessoas_pkey" ON "cup"."relacionamentobempessoas" ("idrelacionamentobempessoa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "relacionamentos_pkey" ON "cup"."relacionamentos" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "renda_pkey" ON "cup"."renda" ("idrenda") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "telefones_pkey" ON "cup"."telefones" ("idtelefone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_pessoa" ON "cup"."pessoa" ("idpessoa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "bempessoa_pkey" ON "cup"."bempessoa" ("idbempessoa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "bemproducaoagricola_pkey" ON "cup"."bemproducaoagricola" ("idproducaoagricola") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_semovente" ON "cup"."bemsemovente" ("idbemsemovente") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "caracteristicacondominio_pkey" ON "cup"."caracteristicacondominio" ("idcaracteristicacondominio") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "caracteristicasimovel_pkey" ON "cup"."caracteristicasimovel" ("idcaracteristicas") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "comodos_pkey" ON "cup"."comodos" ("idcomodos") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "garagemvinculada_pkey" ON "cup"."garagemvinculada" ("idbemgaragem") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_garantia" ON "cup"."garantia" ("idgarantia") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_guiatransporte" ON "cup"."guiatransporte" ("idguiatransporte") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_hipoteca" ON "cup"."hipoteca" ("idhipoteca") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_registro" ON "cup"."registro" ("idregistro") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_seguro" ON "cup"."seguro" ("idseguro") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_bens" ON "cup"."bem" ("idbem") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_avaliacao" ON "cup"."avaliacao" ("idavaliacao") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_bemimovel" ON "cup"."bemimovel_old" ("idbem") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_bem_1" ON "cup"."bem_old" ("idbem") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_cargo" ON "cup"."cargo" ("idcargo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_endereco_1" ON "cup"."endereco_old" ("idendereco") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_fisica_1" ON "cup"."fisica_old" ("idpessoa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_juridica_1" ON "cup"."juridica_old" ("idpessoa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "marcacoesnoregistrocadastral_pkey" ON "cup"."marcacoesnoregistrocadastral" ("idmarcacaopessoa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "rendas_pkey" ON "cup"."rendas" ("idrenda") `);
        await queryRunner.query(`ALTER TABLE "cup"."bemequipamento" ADD CONSTRAINT "FK_197dc040e56986b2a1f0eb58dc3" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ADD CONSTRAINT "FK_79ddc3d2df3592e576b6a26138b" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ADD CONSTRAINT "FK_2f98c3ea86926347fab4085b0f1" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmaquina" ADD CONSTRAINT "FK_80083602ff56d961706b60df0af" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmovel" ADD CONSTRAINT "FK_e2d4e1ad3255ba9e209fbc37510" FOREIGN KEY ("bem_idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonialvalores" ADD CONSTRAINT "FK_c93b6bf979560ec68bf8fc3a616" FOREIGN KEY ("idbalancopatrimonial") REFERENCES "cup"."balancopatrimonial"("idbalancopatrimonial") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonial" ADD CONSTRAINT "FK_d4f238092af721f9e1ee7c1f80d" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bensvinculados" ADD CONSTRAINT "FK_83444a3617d201fbbd1fec79e86" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bensvinculados" ADD CONSTRAINT "FK_08c7e4404c6617b4c22507cb128" FOREIGN KEY ("idbemprincipal") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ADD CONSTRAINT "FK_5aa1fc2adadc703da198fc6e19b" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."cargoocupacao" ADD CONSTRAINT "FK_b0a0670300e4207b8b349ef0dfa" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."certidao" ADD CONSTRAINT "FK_737474cb269356f1e72be6d92d5" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."controlecapital" ADD CONSTRAINT "FK_6392592c0dc4d47c6edd523b33c" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."dirigenteempresa" ADD CONSTRAINT "FK_d54161b82cc0225e34a2343766a" FOREIGN KEY ("idpessoafisica") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."dirigenteempresa" ADD CONSTRAINT "FK_6fb8550e03b9e1f830ef2063847" FOREIGN KEY ("idpessoajuridica") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ADD CONSTRAINT "FK_4d359ec0e2c5dc1373f965eab3f" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ADD CONSTRAINT "FK_8550da69c13259ca5b5c48f1e8d" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ADD CONSTRAINT "FK_0b581de1f4933ade3dcc3da86b7" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" ADD CONSTRAINT "FK_6895c4733c5a99cf8a693985612" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" ADD CONSTRAINT "FK_d944af6e0aa53d06da9b5c550cd" FOREIGN KEY ("idregimetributacao") REFERENCES "cup"."regimetributacao"("idregimetributacao") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ADD CONSTRAINT "FK_131e917c2e8ee3407f2a55f96a3" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ADD CONSTRAINT "FK_5136182491cb35b777cc8af8e6f" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ADD CONSTRAINT "FK_c7bd5c11ae54172369a26ecf343" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ADD CONSTRAINT "FK_ed8cf74b81e329fe54bb2d91f6d" FOREIGN KEY ("idpessoarelacionada") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."renda" ADD CONSTRAINT "FK_5f76b91a2c95b94ea4ca146beec" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ADD CONSTRAINT "FK_180355bb955ef0891373e9a708b" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bempessoa" ADD CONSTRAINT "FK_53d188a4afb63c5e393ef7d0fa1" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bempessoa" ADD CONSTRAINT "FK_a015897b7b83f36ce2fb2088b3a" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemproducaoagricola" ADD CONSTRAINT "FK_d011c4199d4991c8dfd28a85f51" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemsemovente" ADD CONSTRAINT "FK_0e60e03a1bd5220e48c14f2cab7" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ADD CONSTRAINT "FK_e6559e1e52f8425fa4696142ba3" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ADD CONSTRAINT "FK_bcabee43230b104765835fac395" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ADD CONSTRAINT "FK_11b0e343da7f56694da29098169" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."garagemvinculada" ADD CONSTRAINT "FK_44bf7b74a4a3fecc9bd1b0ed117" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."garantia" ADD CONSTRAINT "FK_7e91dd8acbee4171a8c6e82db9b" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."guiatransporte" ADD CONSTRAINT "FK_fc4b507155dd598920738a90a34" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."hipoteca" ADD CONSTRAINT "FK_4f2e60c9dd35ab26823a92cc16c" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."registro" ADD CONSTRAINT "FK_050aee7f066ea1fd8fbbe3c0630" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."seguro" ADD CONSTRAINT "FK_e5124609748d52a7a15bb81a031" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."avaliacao" ADD CONSTRAINT "FK_511c09433a628f3726ba08fa831" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cup"."avaliacao" DROP CONSTRAINT "FK_511c09433a628f3726ba08fa831"`);
        await queryRunner.query(`ALTER TABLE "cup"."seguro" DROP CONSTRAINT "FK_e5124609748d52a7a15bb81a031"`);
        await queryRunner.query(`ALTER TABLE "cup"."registro" DROP CONSTRAINT "FK_050aee7f066ea1fd8fbbe3c0630"`);
        await queryRunner.query(`ALTER TABLE "cup"."hipoteca" DROP CONSTRAINT "FK_4f2e60c9dd35ab26823a92cc16c"`);
        await queryRunner.query(`ALTER TABLE "cup"."guiatransporte" DROP CONSTRAINT "FK_fc4b507155dd598920738a90a34"`);
        await queryRunner.query(`ALTER TABLE "cup"."garantia" DROP CONSTRAINT "FK_7e91dd8acbee4171a8c6e82db9b"`);
        await queryRunner.query(`ALTER TABLE "cup"."garagemvinculada" DROP CONSTRAINT "FK_44bf7b74a4a3fecc9bd1b0ed117"`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" DROP CONSTRAINT "FK_11b0e343da7f56694da29098169"`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" DROP CONSTRAINT "FK_bcabee43230b104765835fac395"`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" DROP CONSTRAINT "FK_e6559e1e52f8425fa4696142ba3"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemsemovente" DROP CONSTRAINT "FK_0e60e03a1bd5220e48c14f2cab7"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemproducaoagricola" DROP CONSTRAINT "FK_d011c4199d4991c8dfd28a85f51"`);
        await queryRunner.query(`ALTER TABLE "cup"."bempessoa" DROP CONSTRAINT "FK_a015897b7b83f36ce2fb2088b3a"`);
        await queryRunner.query(`ALTER TABLE "cup"."bempessoa" DROP CONSTRAINT "FK_53d188a4afb63c5e393ef7d0fa1"`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" DROP CONSTRAINT "FK_180355bb955ef0891373e9a708b"`);
        await queryRunner.query(`ALTER TABLE "cup"."renda" DROP CONSTRAINT "FK_5f76b91a2c95b94ea4ca146beec"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" DROP CONSTRAINT "FK_ed8cf74b81e329fe54bb2d91f6d"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" DROP CONSTRAINT "FK_c7bd5c11ae54172369a26ecf343"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" DROP CONSTRAINT "FK_5136182491cb35b777cc8af8e6f"`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" DROP CONSTRAINT "FK_131e917c2e8ee3407f2a55f96a3"`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" DROP CONSTRAINT "FK_d944af6e0aa53d06da9b5c550cd"`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" DROP CONSTRAINT "FK_6895c4733c5a99cf8a693985612"`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" DROP CONSTRAINT "FK_0b581de1f4933ade3dcc3da86b7"`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" DROP CONSTRAINT "FK_8550da69c13259ca5b5c48f1e8d"`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" DROP CONSTRAINT "FK_4d359ec0e2c5dc1373f965eab3f"`);
        await queryRunner.query(`ALTER TABLE "cup"."dirigenteempresa" DROP CONSTRAINT "FK_6fb8550e03b9e1f830ef2063847"`);
        await queryRunner.query(`ALTER TABLE "cup"."dirigenteempresa" DROP CONSTRAINT "FK_d54161b82cc0225e34a2343766a"`);
        await queryRunner.query(`ALTER TABLE "cup"."controlecapital" DROP CONSTRAINT "FK_6392592c0dc4d47c6edd523b33c"`);
        await queryRunner.query(`ALTER TABLE "cup"."certidao" DROP CONSTRAINT "FK_737474cb269356f1e72be6d92d5"`);
        await queryRunner.query(`ALTER TABLE "cup"."cargoocupacao" DROP CONSTRAINT "FK_b0a0670300e4207b8b349ef0dfa"`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" DROP CONSTRAINT "FK_5aa1fc2adadc703da198fc6e19b"`);
        await queryRunner.query(`ALTER TABLE "cup"."bensvinculados" DROP CONSTRAINT "FK_08c7e4404c6617b4c22507cb128"`);
        await queryRunner.query(`ALTER TABLE "cup"."bensvinculados" DROP CONSTRAINT "FK_83444a3617d201fbbd1fec79e86"`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonial" DROP CONSTRAINT "FK_d4f238092af721f9e1ee7c1f80d"`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonialvalores" DROP CONSTRAINT "FK_c93b6bf979560ec68bf8fc3a616"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmovel" DROP CONSTRAINT "FK_e2d4e1ad3255ba9e209fbc37510"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmaquina" DROP CONSTRAINT "FK_80083602ff56d961706b60df0af"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" DROP CONSTRAINT "FK_2f98c3ea86926347fab4085b0f1"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" DROP CONSTRAINT "FK_79ddc3d2df3592e576b6a26138b"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemequipamento" DROP CONSTRAINT "FK_197dc040e56986b2a1f0eb58dc3"`);
        await queryRunner.query(`DROP INDEX "cup"."rendas_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."marcacoesnoregistrocadastral_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_juridica_1"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_fisica_1"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_endereco_1"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_cargo"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_bem_1"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_bemimovel"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_avaliacao"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_bens"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_seguro"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_registro"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_hipoteca"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_guiatransporte"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_garantia"`);
        await queryRunner.query(`DROP INDEX "cup"."garagemvinculada_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."comodos_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."caracteristicasimovel_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."caracteristicacondominio_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_semovente"`);
        await queryRunner.query(`DROP INDEX "cup"."bemproducaoagricola_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."bempessoa_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_pessoa"`);
        await queryRunner.query(`DROP INDEX "cup"."telefones_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."renda_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."relacionamentos_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."relacionamentobempessoas_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_regimepessoa"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_regimetributacao"`);
        await queryRunner.query(`DROP INDEX "cup"."juridica_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."fisica_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."endereco_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_dirigenteempresa"`);
        await queryRunner.query(`DROP INDEX "cup"."controlecapital_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_certidoes"`);
        await queryRunner.query(`DROP INDEX "cup"."cargoocupacao_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."capitalsocial_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."bensvinculados_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_balancopatri"`);
        await queryRunner.query(`DROP INDEX "cup"."balancopatrimonialvalores_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_bemmovel"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_bemmaquina"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_bemlaudo"`);
        await queryRunner.query(`DROP INDEX "cup"."bemimovel_pkey"`);
        await queryRunner.query(`DROP INDEX "cup"."pk_bemequipamento"`);
        await queryRunner.query(`ALTER TABLE "cup"."rendas" ALTER COLUMN "valor" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."rendas" ALTER COLUMN "idtiporenda" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."rendas" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idimpeditivos" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idrestritivo" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idrisco" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idcontrole" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idstatus" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idsufixo" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."marcacoesnoregistrocadastral" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica_old" ALTER COLUMN "incentivoicms" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco_old" ALTER COLUMN "idendereco" SET DEFAULT nextval('cup.endereco_seq')`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco_old" ALTER COLUMN "idendereco" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "cup"."endereco_old_idendereco_seq"`);
        await queryRunner.query(`ALTER TABLE "cup"."bem_old" ALTER COLUMN "idbem" SET DEFAULT nextval('cup.bem_seq')`);
        await queryRunner.query(`ALTER TABLE "cup"."bem_old" ALTER COLUMN "idbem" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "cup"."bem_old_idbem_seq"`);
        await queryRunner.query(`ALTER TABLE "cup"."avaliacao" ALTER COLUMN "idavaliacao" SET DEFAULT nextval('cup.avaliacao_seq')`);
        await queryRunner.query(`ALTER TABLE "cup"."avaliacao" ALTER COLUMN "idavaliacao" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "cup"."avaliacao_idavaliacao_seq"`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idestacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idusuario" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idcdestaque" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idanunciado" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "sitioweb" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idcfotos" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idcplaca" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idade" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idestadoconservacao" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idsituacaobem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "valor" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "situacaogarantia" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "qtdbensassociados" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "nomebem" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "referencia" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idtipobem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idbem" SET DEFAULT nextval('cup.bem2_idbem_seq')`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idbem" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "cup"."bem_idbem_seq"`);
        await queryRunner.query(`ALTER TABLE "cup"."bem" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."seguro" ALTER COLUMN "idseguro" SET DEFAULT nextval('cup.seguro_seq')`);
        await queryRunner.query(`ALTER TABLE "cup"."seguro" ALTER COLUMN "idseguro" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "cup"."seguro_idseguro_seq"`);
        await queryRunner.query(`ALTER TABLE "cup"."guiatransporte" ALTER COLUMN "idguiatransporte" SET DEFAULT nextval('cup.guiatransporte_seq')`);
        await queryRunner.query(`ALTER TABLE "cup"."guiatransporte" ALTER COLUMN "idguiatransporte" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "cup"."guiatransporte_idguiatransporte_seq"`);
        await queryRunner.query(`ALTER TABLE "cup"."garagemvinculada" ALTER COLUMN "idbem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "nrodependencias" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "nrolavabos" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "nrosalas" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "nrosuites" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "qtddormitorios" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "idbem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "idcbombahidraulica" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "identificacaohobbybox" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "idchobbybox" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "localizacaogaragem" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "tipogaragem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "identificacaogaragens" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "qtdgaragens" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "idbem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "torre" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "nropavimentos" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcvidroisolamento" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "nomecondominioabreviado" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "nomecondominio" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "tipoaquecedor" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcelevador" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcarealazer" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcduplaentrada" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idcpilotis" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idbem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoa" ALTER COLUMN "idpessoa" SET DEFAULT nextval('cup.pessoa_seq')`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoa" ALTER COLUMN "idpessoa" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "cup"."pessoa_idpessoa_seq"`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ALTER COLUMN "falarcom" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ALTER COLUMN "idccelular" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ALTER COLUMN "pais" SET DEFAULT '55'`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ALTER COLUMN "numero" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ALTER COLUMN "idpessoarelacionada" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ALTER COLUMN "idnaturezatipo" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idnaturezarelacionamento" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idtipobem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idbem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ALTER COLUMN "idproprietario" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" ALTER COLUMN "aliquota" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "idestacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "idusuario" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "inscricaomunicipal" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "grupoeconomico" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "optantesimples" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "incentivoicms" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "inscricaoestadual" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "orgaoexpedidor" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "numeroregistrojunta" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "senha" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idestacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idusuario" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "status" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "codigousuariorede" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "ndependente" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "ufrg" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "orgaoemissor" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "registrogeral" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "ufnaturalidade" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "profissao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idsexo" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idestadocivil" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "nomepai" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "apelido" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idestacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idusuario" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "torre" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idccorrespondencia" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idtipoendereco" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "caixapostal" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "cep" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "perimetro" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "complemento" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "tipologradouro" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ALTER COLUMN "idpessoa" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."controlecapital" ALTER COLUMN "idpessoa" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."controlecapital" ALTER COLUMN "valor" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."cargoocupacao" ALTER COLUMN "status" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."cargoocupacao" ALTER COLUMN "denominacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ALTER COLUMN "valorcota" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ALTER COLUMN "integralizado" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ALTER COLUMN "subscrito" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ALTER COLUMN "autorizado" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmaquina" DROP CONSTRAINT "UQ_80083602ff56d961706b60df0af"`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ALTER COLUMN "valorfinal" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ALTER COLUMN "valorcoisafeita" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ALTER COLUMN "percentualbdi" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ALTER COLUMN "precocub" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idestacao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idusuario" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idcaracteristicacondominio" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idcomodos" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "sacadas" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idcaracteristicas" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idesquina" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idchurrasqueira" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idtipogas" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idprontaentrega" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idlocalchave" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idregiao" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idaforamento" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idchabitese" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idtipoescritura" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaoonus" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "areareal" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "arealegal" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaopenhora" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaoexploracao" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaocondominio" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "situacaoimuneitr" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "numeroimovelincra" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "numeroimovelrf" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "areaconstruida" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "areatotal" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idregimeobra" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "nroapartamento" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idsubtipobemimovel" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ALTER COLUMN "idbem" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "cup"."bemequipamento" DROP CONSTRAINT "UQ_197dc040e56986b2a1f0eb58dc3"`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" DROP CONSTRAINT "pk_regimepessoa"`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" ADD CONSTRAINT "pk_regimepessoa" PRIMARY KEY ("idpessoa")`);
        await queryRunner.query(`ALTER TABLE "cup"."certidao" DROP CONSTRAINT "pk_certidoes"`);
        await queryRunner.query(`ALTER TABLE "cup"."certidao" ADD CONSTRAINT "pk_certidoes" PRIMARY KEY ("idpessoa", "dataemissao", "numero")`);
        await queryRunner.query(`ALTER TABLE "cup"."avaliacao" ADD CONSTRAINT "fk_avaliacaobem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."seguro" ADD CONSTRAINT "fk_segurobem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."registro" ADD CONSTRAINT "fk_escriturabem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."hipoteca" ADD CONSTRAINT "fk_bemhipoteca" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."guiatransporte" ADD CONSTRAINT "fk_transportebem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."garantia" ADD CONSTRAINT "fk_bemgarantia" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."garagemvinculada" ADD CONSTRAINT "fk_bemgaragem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."comodos" ADD CONSTRAINT "fk_comodosbem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicasimovel" ADD CONSTRAINT "fk_caractbem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."caracteristicacondominio" ADD CONSTRAINT "fk_caractercondominio" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemsemovente" ADD CONSTRAINT "fk_bemsemovente" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemproducaoagricola" ADD CONSTRAINT "fk_bemproducao" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bempessoa" ADD CONSTRAINT "fk_bempessoas" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bempessoa" ADD CONSTRAINT "fk_bembens" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."telefones" ADD CONSTRAINT "fk_telpessoa" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."renda" ADD CONSTRAINT "renda_idpessoa_fkey" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ADD CONSTRAINT "fk_tiporelac" FOREIGN KEY ("idnaturezatipo") REFERENCES "apoio"."tiporelacionamento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ADD CONSTRAINT "fk_relacpessoa" FOREIGN KEY ("idpessoarelacionada") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentos" ADD CONSTRAINT "fk_pessoarelac" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ADD CONSTRAINT "fk_relacbempessoa" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."relacionamentobempessoas" ADD CONSTRAINT "fk_bemrelac" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" ADD CONSTRAINT "fk_tipotributacao" FOREIGN KEY ("idregimetributacao") REFERENCES "cup"."regimetributacao"("idregimetributacao") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."pessoaregimetributacao" ADD CONSTRAINT "fk_regimetripessoa" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."juridica" ADD CONSTRAINT "pessoaJuridica" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."fisica" ADD CONSTRAINT "pessoaFisica" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."endereco" ADD CONSTRAINT "fk_pessoaendereco" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."dirigenteempresa" ADD CONSTRAINT "fk_empresa" FOREIGN KEY ("idpessoajuridica") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."dirigenteempresa" ADD CONSTRAINT "fk_dirigente" FOREIGN KEY ("idpessoafisica") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."controlecapital" ADD CONSTRAINT "fk_pessoacapital" FOREIGN KEY ("idpessoa", "idpessoa") REFERENCES "cup"."pessoa"("idpessoa","idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."certidao" ADD CONSTRAINT "fk_certidaopessoa" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."cargoocupacao" ADD CONSTRAINT "fk_ocupacaopessoa" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."capitalsocial" ADD CONSTRAINT "fk_pessoacapital" FOREIGN KEY ("idpessoa", "idpessoa") REFERENCES "cup"."pessoa"("idpessoa","idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bensvinculados" ADD CONSTRAINT "fk_pessoavenculo" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bensvinculados" ADD CONSTRAINT "fk_bemvinculado" FOREIGN KEY ("idbemprincipal") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonial" ADD CONSTRAINT "fk_pessoabalancopatr" FOREIGN KEY ("idpessoa") REFERENCES "cup"."pessoa"("idpessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonial" ADD CONSTRAINT "fk_grupocentrocusto" FOREIGN KEY ("idgrupocentrocusto") REFERENCES "apoio"."grupocentrocusto"("idgrupoCentroCusto") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonial" ADD CONSTRAINT "fk_balancocentrocusto" FOREIGN KEY ("idcentrocusto") REFERENCES "apoio"."centrocusto"("idcentrocusto") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonialvalores" ADD CONSTRAINT "fk_centrocustobal" FOREIGN KEY ("idcentrocusto") REFERENCES "apoio"."centrocusto"("idcentrocusto") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."balancopatrimonialvalores" ADD CONSTRAINT "fk_balancopatrim" FOREIGN KEY ("idbalancopatrimonial") REFERENCES "cup"."balancopatrimonial"("idbalancopatrimonial") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmovel" ADD CONSTRAINT "fk_imovelbem" FOREIGN KEY ("bem_idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemmaquina" ADD CONSTRAINT "fk_maquinabem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemlaudo" ADD CONSTRAINT "fk_laudobem" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemimovel" ADD CONSTRAINT "fk_bemimovel" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cup"."bemequipamento" ADD CONSTRAINT "fk_bemequip" FOREIGN KEY ("idbem") REFERENCES "cup"."bem"("idbem") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
