import { MigrationInterface, QueryRunner } from "typeorm";

export class migrations1681590312869 implements MigrationInterface {
    name = 'migrations1681590312869'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" DROP CONSTRAINT "empresa"`);
        await queryRunner.query(`CREATE TABLE "customobra"."customobra" ("id" SERIAL NOT NULL, "bem" character varying(50) NOT NULL, "anosvidautil" integer, "taxadepreciavelmes" numeric(10,2) DEFAULT 0, CONSTRAINT "PK_d45ddcb874a80ab52ce6611eb0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "customobra.depreciacao_pkey" ON "customobra"."customobra" ("id") `);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."clientes_empresa_seq" OWNED BY "customobra"."clientes"."empresa"`);
        await queryRunner.query(`ALTER TABLE "customobra"."clientes" ALTER COLUMN "empresa" SET DEFAULT nextval('"customobra"."clientes_empresa_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."clientes" ALTER COLUMN "empresa" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."amortizacaodecapital_codigo_seq" OWNED BY "customobra"."amortizacaodecapital"."codigo"`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ALTER COLUMN "codigo" SET DEFAULT nextval('"customobra"."amortizacaodecapital_codigo_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ALTER COLUMN "taxaamortizacao" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ALTER COLUMN "dataapuracao" TYPE TIMESTAMP`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."categorias_codigo_seq" OWNED BY "customobra"."categorias"."codigo"`);
        await queryRunner.query(`ALTER TABLE "customobra"."categorias" ALTER COLUMN "codigo" SET DEFAULT nextval('"customobra"."categorias_codigo_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."categorias" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."demonstrativodedespesas_iddespesa_seq" OWNED BY "customobra"."demonstrativodedespesas"."iddespesa"`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodedespesas" ALTER COLUMN "iddespesa" SET DEFAULT nextval('"customobra"."demonstrativodedespesas_iddespesa_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodedespesas" ALTER COLUMN "iddespesa" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodedespesas" ALTER COLUMN "dataevento" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodedespesas" ALTER COLUMN "valor" TYPE real(24)`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."demonstrativodeencargoseimpostos_idencargoimposto_seq" OWNED BY "customobra"."demonstrativodeencargoseimpostos"."idencargoimposto"`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodeencargoseimpostos" ALTER COLUMN "idencargoimposto" SET DEFAULT nextval('"customobra"."demonstrativodeencargoseimpostos_idencargoimposto_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodeencargoseimpostos" ALTER COLUMN "idencargoimposto" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodeencargoseimpostos" ALTER COLUMN "taxapercentualmes" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."depreciacao" ALTER COLUMN "taxadepreciavelmes" TYPE real(24)`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."encargossociaisbasicos_codigoencargo_seq" OWNED BY "customobra"."encargossociaisbasicos"."codigoencargo"`);
        await queryRunner.query(`ALTER TABLE "customobra"."encargossociaisbasicos" ALTER COLUMN "codigoencargo" SET DEFAULT nextval('"customobra"."encargossociaisbasicos_codigoencargo_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."encargossociaisbasicos" ALTER COLUMN "codigoencargo" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."encargossociaisbasicos" ALTER COLUMN "taxapercentualmes" TYPE real(24)`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."horasefetivamentepagasanuais_codigo_seq" OWNED BY "customobra"."horasefetivamentepagasanuais"."codigo"`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasefetivamentepagasanuais" ALTER COLUMN "codigo" SET DEFAULT nextval('"customobra"."horasefetivamentepagasanuais_codigo_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasefetivamentepagasanuais" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasefetivamentepagasanuais" ALTER COLUMN "horascentesimais" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasefetivamentepagasanuais" ALTER COLUMN "horasano" TYPE double precision(53)`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."horasimprodutivas_codigo_seq" OWNED BY "customobra"."horasimprodutivas"."codigo"`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasimprodutivas" ALTER COLUMN "codigo" SET DEFAULT nextval('"customobra"."horasimprodutivas_codigo_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasimprodutivas" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasimprodutivas" ALTER COLUMN "HorasCentesimais" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasimprodutivas" ALTER COLUMN "horasano" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."irrfonte" ALTER COLUMN "ValorInicial" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "customobra"."irrfonte" ALTER COLUMN "ValorFinal" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "customobra"."irrfonte" ALTER COLUMN "Aliquota" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "customobra"."irrfonte" ALTER COLUMN "ValorReducao" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "customobra"."lucrominimo" ALTER COLUMN "taxadelucro" TYPE real(24)`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."maodeobranaoprodutiva_codigo_seq" OWNED BY "customobra"."maodeobranaoprodutiva"."codigo"`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobranaoprodutiva" ALTER COLUMN "codigo" SET DEFAULT nextval('"customobra"."maodeobranaoprodutiva_codigo_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobranaoprodutiva" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."maodeobraprodutiva_codigo_seq" OWNED BY "customobra"."maodeobraprodutiva"."codigo"`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobraprodutiva" ALTER COLUMN "codigo" SET DEFAULT nextval('"customobra"."maodeobraprodutiva_codigo_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobraprodutiva" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobraprodutiva" ALTER COLUMN "produtividade" TYPE double precision(53)`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."maquinasequipamentosferramentas_sequencia_seq" OWNED BY "customobra"."maquinasequipamentosferramentas"."sequencia"`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "sequencia" SET DEFAULT nextval('"customobra"."maquinasequipamentosferramentas_sequencia_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "sequencia" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "datadeaquisicao" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "vidadepreciavel" TYPE real(24)`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "taxadepreciavelmes" TYPE real(24)`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."setor_idsetor_seq" OWNED BY "customobra"."setor"."idsetor"`);
        await queryRunner.query(`ALTER TABLE "customobra"."setor" ALTER COLUMN "idsetor" SET DEFAULT nextval('"customobra"."setor_idsetor_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."setor" ALTER COLUMN "idsetor" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."tipodeencargo_old_idtipoencargo_seq" OWNED BY "customobra"."tipodeencargo_old"."idtipoencargo"`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodeencargo_old" ALTER COLUMN "idtipoencargo" SET DEFAULT nextval('"customobra"."tipodeencargo_old_idtipoencargo_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodeencargo_old" ALTER COLUMN "idtipoencargo" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."tipodeinvestimento_idtipoinvestimento_seq" OWNED BY "customobra"."tipodeinvestimento"."idtipoinvestimento"`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodeinvestimento" ALTER COLUMN "idtipoinvestimento" SET DEFAULT nextval('"customobra"."tipodeinvestimento_idtipoinvestimento_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodeinvestimento" ALTER COLUMN "idtipoinvestimento" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "customobra"."tipodespesa_idtipodespesa_seq" OWNED BY "customobra"."tipodespesa"."idtipodespesa"`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodespesa" ALTER COLUMN "idtipodespesa" SET DEFAULT nextval('"customobra"."tipodespesa_idtipodespesa_seq"')`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodespesa" ALTER COLUMN "idtipodespesa" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "somasubtotal" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "hsmes" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "comencargos" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "despmensal" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "amort" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "imob" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "deprec" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "iss" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "lucr" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "custo1" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "custo2" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "custo3" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "custo4" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "chsinicial" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "chssemlucro" TYPE double precision(53)`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "maodeobracomlucro" TYPE double precision(53)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "clientes_pk" ON "customobra"."clientes" ("empresa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "amortizacaodecapital_pk" ON "customobra"."amortizacaodecapital" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_categorias" ON "customobra"."categorias" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "demostrativodedespesas_pk" ON "customobra"."demonstrativodedespesas" ("iddespesa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_demonstrativodeencargoseimpostos" ON "customobra"."demonstrativodeencargoseimpostos" ("idencargoimposto") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "depreciacao_pkey" ON "customobra"."depreciacao" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "encargossociaisbasicos_pk" ON "customobra"."encargossociaisbasicos" ("codigoencargo", "empresa", "idtipodeencargo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "horasefetivamentepagasanuais_pk" ON "customobra"."horasefetivamentepagasanuais" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "horasimprodutivas_pk" ON "customobra"."horasimprodutivas" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "irrfonte_pkey" ON "customobra"."irrfonte" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "lucrominimo_pk" ON "customobra"."lucrominimo" ("empresa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "maodeobranaoprodutiva_pk" ON "customobra"."maodeobranaoprodutiva" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "maodeobraprodutiva_pk" ON "customobra"."maodeobraprodutiva" ("codigo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "maquinasequipamentosferramentas_pk" ON "customobra"."maquinasequipamentosferramentas" ("categoria", "empresa", "idsetor", "sequencia", "subcategoria") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "progressaoinss_pkey" ON "customobra"."progressaoinss" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "setor_pk" ON "customobra"."setor" ("idsetor") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_tipodeencargo" ON "customobra"."tipodeencargo" ("idtipodeencargo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipodeencargo_pkey" ON "customobra"."tipodeencargo_old" ("idtipoencargo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_tipodeinvestimento" ON "customobra"."tipodeinvestimento" ("idtipoinvestimento") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "pk_tipodespesa" ON "customobra"."tipodespesa" ("idtipodespesa") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "view_customaodeobras_pkey" ON "customobra"."view_customaodeobras" ("id") `);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ADD CONSTRAINT "FK_67b40d7929415206ca693206c9a" FOREIGN KEY ("empresa") REFERENCES "customobra"."clientes"("empresa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" DROP CONSTRAINT "FK_67b40d7929415206ca693206c9a"`);
        await queryRunner.query(`DROP INDEX "customobra"."view_customaodeobras_pkey"`);
        await queryRunner.query(`DROP INDEX "customobra"."pk_tipodespesa"`);
        await queryRunner.query(`DROP INDEX "customobra"."pk_tipodeinvestimento"`);
        await queryRunner.query(`DROP INDEX "customobra"."tipodeencargo_pkey"`);
        await queryRunner.query(`DROP INDEX "customobra"."pk_tipodeencargo"`);
        await queryRunner.query(`DROP INDEX "customobra"."setor_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."progressaoinss_pkey"`);
        await queryRunner.query(`DROP INDEX "customobra"."maquinasequipamentosferramentas_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."maodeobraprodutiva_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."maodeobranaoprodutiva_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."lucrominimo_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."irrfonte_pkey"`);
        await queryRunner.query(`DROP INDEX "customobra"."horasimprodutivas_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."horasefetivamentepagasanuais_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."encargossociaisbasicos_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."depreciacao_pkey"`);
        await queryRunner.query(`DROP INDEX "customobra"."pk_demonstrativodeencargoseimpostos"`);
        await queryRunner.query(`DROP INDEX "customobra"."demostrativodedespesas_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."pk_categorias"`);
        await queryRunner.query(`DROP INDEX "customobra"."amortizacaodecapital_pk"`);
        await queryRunner.query(`DROP INDEX "customobra"."clientes_pk"`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "maodeobracomlucro" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "chssemlucro" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "chsinicial" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "custo4" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "custo3" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "custo2" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "custo1" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "lucr" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "iss" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "deprec" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "imob" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "amort" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "despmensal" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "comencargos" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "hsmes" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."view_customaodeobras" ALTER COLUMN "somasubtotal" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodespesa" ALTER COLUMN "idtipodespesa" SET DEFAULT nextval('customobra.tipodespesa_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodespesa" ALTER COLUMN "idtipodespesa" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."tipodespesa_idtipodespesa_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodeinvestimento" ALTER COLUMN "idtipoinvestimento" SET DEFAULT nextval('customobra.tipodeinvestimento_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodeinvestimento" ALTER COLUMN "idtipoinvestimento" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."tipodeinvestimento_idtipoinvestimento_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodeencargo_old" ALTER COLUMN "idtipoencargo" SET DEFAULT nextval('customobra.tipodeencargo_idtipoencargo_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."tipodeencargo_old" ALTER COLUMN "idtipoencargo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."tipodeencargo_old_idtipoencargo_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."setor" ALTER COLUMN "idsetor" SET DEFAULT nextval('customobra.setor_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."setor" ALTER COLUMN "idsetor" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."setor_idsetor_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "taxadepreciavelmes" TYPE real`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "vidadepreciavel" TYPE real`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "datadeaquisicao" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "sequencia" SET DEFAULT nextval('customobra.maquinasequipamentosferramentas_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."maquinasequipamentosferramentas" ALTER COLUMN "sequencia" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."maquinasequipamentosferramentas_sequencia_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobraprodutiva" ALTER COLUMN "produtividade" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobraprodutiva" ALTER COLUMN "codigo" SET DEFAULT nextval('customobra.maodeobraprodutiva_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobraprodutiva" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."maodeobraprodutiva_codigo_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobranaoprodutiva" ALTER COLUMN "codigo" SET DEFAULT nextval('customobra.maodeobranaoprodutiva_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."maodeobranaoprodutiva" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."maodeobranaoprodutiva_codigo_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."lucrominimo" ALTER COLUMN "taxadelucro" TYPE real`);
        await queryRunner.query(`ALTER TABLE "customobra"."irrfonte" ALTER COLUMN "ValorReducao" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customobra"."irrfonte" ALTER COLUMN "Aliquota" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customobra"."irrfonte" ALTER COLUMN "ValorFinal" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customobra"."irrfonte" ALTER COLUMN "ValorInicial" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasimprodutivas" ALTER COLUMN "horasano" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasimprodutivas" ALTER COLUMN "HorasCentesimais" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasimprodutivas" ALTER COLUMN "codigo" SET DEFAULT nextval('customobra.horasimprodutivas_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasimprodutivas" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."horasimprodutivas_codigo_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasefetivamentepagasanuais" ALTER COLUMN "horasano" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasefetivamentepagasanuais" ALTER COLUMN "horascentesimais" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasefetivamentepagasanuais" ALTER COLUMN "codigo" SET DEFAULT nextval('customobra.horasefetivamentepagasanuais_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."horasefetivamentepagasanuais" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."horasefetivamentepagasanuais_codigo_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."encargossociaisbasicos" ALTER COLUMN "taxapercentualmes" TYPE real`);
        await queryRunner.query(`ALTER TABLE "customobra"."encargossociaisbasicos" ALTER COLUMN "codigoencargo" SET DEFAULT nextval('customobra.encargossociaisbasicos_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."encargossociaisbasicos" ALTER COLUMN "codigoencargo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."encargossociaisbasicos_codigoencargo_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."depreciacao" ALTER COLUMN "taxadepreciavelmes" TYPE real`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodeencargoseimpostos" ALTER COLUMN "taxapercentualmes" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodeencargoseimpostos" ALTER COLUMN "idencargoimposto" SET DEFAULT nextval('customobra.demonstrativodeencargoseimpostos_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodeencargoseimpostos" ALTER COLUMN "idencargoimposto" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."demonstrativodeencargoseimpostos_idencargoimposto_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodedespesas" ALTER COLUMN "valor" TYPE real`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodedespesas" ALTER COLUMN "dataevento" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodedespesas" ALTER COLUMN "iddespesa" SET DEFAULT nextval('customobra.demostrativodedespesas_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."demonstrativodedespesas" ALTER COLUMN "iddespesa" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."demonstrativodedespesas_iddespesa_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."categorias" ALTER COLUMN "codigo" SET DEFAULT nextval('customobra.categorias_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."categorias" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."categorias_codigo_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ALTER COLUMN "dataapuracao" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ALTER COLUMN "taxaamortizacao" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ALTER COLUMN "codigo" SET DEFAULT nextval('customobra.amortizacaodecapital_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ALTER COLUMN "codigo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."amortizacaodecapital_codigo_seq"`);
        await queryRunner.query(`ALTER TABLE "customobra"."clientes" ALTER COLUMN "empresa" SET DEFAULT nextval('customobra.clientes_seq')`);
        await queryRunner.query(`ALTER TABLE "customobra"."clientes" ALTER COLUMN "empresa" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "customobra"."clientes_empresa_seq"`);
        await queryRunner.query(`DROP INDEX "customobra"."customobra.depreciacao_pkey"`);
        await queryRunner.query(`DROP TABLE "customobra"."customobra"`);
        await queryRunner.query(`ALTER TABLE "customobra"."amortizacaodecapital" ADD CONSTRAINT "empresa" FOREIGN KEY ("empresa") REFERENCES "customobra"."clientes"("empresa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
